title: Spencer Braun
logo: "/images/logo.jpeg?raw=true" # your photo (or logo) here
description: >
  First description
  <br><br>
  Second description
  <br><br>
  <a href="https://www.linkedin.com/in/spencerfbraun/">LinkedIn</a>

theme: jekyll-theme-minimal
google_analytics: UA-144357836-1 # your Google Analytics tracking ID here
