baseURL = "https://spencerbraun.github.io/"
languageCode = "en-us"
title = "Spencer Braun"
theme = "archie"
copyright = ""
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
[params]
	mode="light"
	featherIconsCDN=true
	subtitle = ""
	favicon = "/favicon.png"

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/spencerbraun"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/spencerfbraun/"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://www.linkedin.com/in/spencerfbraun/"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "About"
url = "/about"
weight = 2


[[menu.main]]
name = "Writing"
url = "/posts"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 5
